---
# file: roles/common/tasks/main.yml
- name: Add common group
  group:
    name={{item.group}}
    gid={{item.gid}}
  with_items: common_user

- name: Add common user
  user:
    name="{{item.name}}"
    password="{{item.password}}"
    uid="{{item.uid}}"
    group="{{item.group}}"
    comment="{{item.name}}"
  with_items: common_user

- name: packages install
  yum: name={{item}} state=present
  with_items:
    - openssh-clients
    - ntp

- name: ip*tables stopped
  service: name={{item}} state=stopped enabled=no
  with_items:
    - ip6tables
    - iptables

- name: ntp setting
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd

- name: ntpd start
  service: name=ntpd state=started enabled=yes

- name: generate hosts files
  lineinfile: dest=/etc/hosts regexp='^{{item}}.*' line="{{item}} {{hostvars[item].ansible_fqdn}} {{hostvars[item].ansible_hostname}}" state=present
  when: hostvars[item].ansible_fqdn is defined
  with_items: groups['all']
